export const techStack = [
  { name: "HTML5", slug: "html5" },
  { name: "CSS3", slug: "css3" },
  { name: "JavaScript", slug: "javascript" },
  { name: "TypeScript", slug: "typescript" },
  { name: "React.js", slug: "react" },
  { name: "Redux.js", slug: "redux" },
  { name: "Next.js", slug: "next-dot-js" },
  { name: "Node.js", slug: "node-dot-js" },
  { name: "Ruby", slug: "ruby" },
  { name: "Ruby on Rails", slug: "rubyonrails" },
  { name: "Python", slug: "python" },
  { name: "Django", slug: "django" },
  { name: "Git", slug: "git" },
  { name: "PostgreSQL", slug: "postgresql" },
  { name: "MySQL", slug: "mysql" },
  { name: "SQLite", slug: "sqlite" },
  { name: "Firebase", slug: "firebase" },
  { name: "MongoDB", slug: "mongodb" },
  { name: "FaunaDB", slug: "faunadb" },
  { name: "Socket.io", slug: "socket-dot-io" },
  { name: "Heroku", slug: "heroku" },
  { name: "Vercel", slug: "vercel" },
];
