export const techStack = [
  { name: "HTML", slug: "html" },
  { name: "CSS", slug: "css" },
  { name: "JavaScript", slug: "javascript" },
  { name: "TypeScript", slug: "typescript" },
  { name: "React.js", slug: "react" },
  { name: "Redux.js", slug: "redux" },
  { name: "Node.js", slug: "nodejs" },
  { name: "Ruby", slug: "ruby" },
  { name: "Ruby on Rails", slug: "rails" },
  { name: "Python", slug: "python" },
  { name: "Django", slug: "django" },
  { name: "Git", slug: "git" },
  { name: "GitHub", slug: "github" },
  { name: "SQL", slug: "sql" },
  { name: "NoSQL", slug: "nosql" },
  { name: "Firebase", slug: "firebase" },
  { name: "Cloud Firestore", slug: "firebase_realtime" },
  { name: "MongoDB", slug: "mongodb" },
  { name: "Web Sockets", slug: "sockets" },
  { name: "Deployment", slug: "heroku" },
];
